name: Run ETL and Upload to BigQuery

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:       # allows manual trigger; how about push?

jobs:
  etl-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

    # This part is different from the other yml file
      - name: Decode GCP service account key
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" > service_account.json

      - name: Set GCP credentials path
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=service_account.json" >> $GITHUB_ENV

#      - name: Run ETL scripts
#        run: |
#          python clean_birds.py
#          python clean_stocks.py
#         python upload_to_bigquery.py

#      - name: Run Upload scripts
#         run: |
#         python upload_to_bigquery.py