name: Run tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest with coverage
        run: pytest app_tests/ --cov=app_modules --cov-report=term-missing

      - name: Run ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          version: latest
